In [5]:
# Ex 2
# Reversing diguts
nmb = 2025
nw = int(str(nmb)[::-1])

In [216]:
# Ex 3
# Sum of last 3 digits
nmb = 2133
nw =[int(i) for i in str(nmb)[-3:]]
sum(nw)

7

In [94]:
# Ex 4
# Reverse
nmb  = 2033
nw = int(str(nmb)[::-1])

check = 0

# 1000,100,100,1
for i in range(len(str(nw))):
    number = int(str(nw)[i])*10**(3-i)
    print(number)
    check+=number

check==nmb

3000
300
0
2


False

In [95]:
# Ex 5
# Calculate distance between to coordinates
import math
a = [2,3]
b = [4,5]

dist = (abs((a[0]-b[0]))**2 + abs((a[1]-b[1]))**2) **(1/2)
math.dist(a,b), dist

(2.8284271247461903, 2.8284271247461903)

In [96]:
# Ex 8
# Is argmstrong Number?
# each digit ^3 and sum eqaul to its number

def is_armstrong(n):
    st = str(n)
    sm = 0
    for i in st:
        inte = int(i)**3
        sm+=inte
    
    if sm==n:
        return True
    else:
        return False
for i in range(100,150):
    print(is_armstrong(i),i,end='  ',sep='-')
    
fl = list(filter(is_armstrong,range(100,1000)))

# Checking if it is correct
def turn_armstrong(n):
    st = str(n)
    sm = 0
    for i in st:
        inte = int(i)**3
        sm+=inte
    return sm

mping = list(map(turn_armstrong, fl))
mping


False-100  False-101  False-102  False-103  False-104  False-105  False-106  False-107  False-108  False-109  False-110  False-111  False-112  False-113  False-114  False-115  False-116  False-117  False-118  False-119  False-120  False-121  False-122  False-123  False-124  False-125  False-126  False-127  False-128  False-129  False-130  False-131  False-132  False-133  False-134  False-135  False-136  False-137  False-138  False-139  False-140  False-141  False-142  False-143  False-144  False-145  False-146  False-147  False-148  False-149  

[153, 370, 371, 407]

In [98]:
# Ex 9
# Narcissistic number
# Sum of each digit raised by amount of difit

def narcissistic(n):
    int_st = str(n)
    sm = 0
    ln = len(int_st)
    for i in int_st:
        rais = int(i)**ln
        sm+=rais
    if sm==n:
        return True
    else:
        return False

# Checking
# Correct, based on chat GPT list
flt = list(filter(narcissistic,range(1,1001)))
flt

[1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407]

### Python input and output Exercises, PG6

In [99]:
# Ex 5
# all factors of given number

def all_factors(n):
    all_fc = []
    for i in range(1,n+1):
        if n%i==0:
            all_fc.append(i)
    return all_fc

all_factors(99)

[1, 3, 9, 11, 33, 99]

In [ ]:
# Ex 6
# Accepting only 5 inputs
# Good example of using While
ln = []

while len(ln)<5:
    x = input("Please enter float: ")
    ln.append(float(x))
print(ln)

### if else, loop, range, PG15

In [ ]:
# Ex 6
# Multiplication table
for i in range(1,11):
    for k in range(1,11):
        print(i*k, end = ' ' * (3 - len(str(i*k))))
    print()


In [1]:
# Ex 9
# All the unique combinations
def combinations(a,b):
    comb_lst = []
    for i in range(a,b+1):
        for k in range(i,b+1):
            if i!=k:
                comb_lst.append((i,k))
    return comb_lst

combinations(2,4)

[(2, 3), (2, 4), (3, 4)]

In [36]:
# Ex 10
# Is prime number?
def is_prime(n):
    cnt = 0
    for i in range(1,n+1):
        if n%i==0:
            cnt+=1
    if cnt<=2:
        return True
    else:
        return False
    
primes = list(filter(is_prime, range(1,101)))
for i in primes:
    print(i, end=" ")

1 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [46]:
# Ex 13
# Can be rights of traigles?

def is_triangle(a,b,c):
    lst_ang = sorted([a,b,c])
    if sum(lst_ang)!=180:
        return False
    if max(lst_ang)>sum(lst_ang[:2]):
        return False
    else:
        return True

is_triangle(150,15,15)

False

In [2]:
# Ex 19
# Some till N

def sum_till(n):
    suming = 0
    for i in range(1,n+1):
        suming+=i
    return suming

lst = [4,5,6,7,10]
list(map(sum_till,lst))

[10, 15, 21, 28, 55]

In [53]:
# Ex 20
# Multiply, without using *
x = 5
y = 7
c = y
for i in range(x-1):
    y+=c
y

35

In [79]:
# Ex 22
# Print following pattern

def printing(n):
    for i in range(1,n+1):
        for k in range(i):
            print(i,end=' ')
        print()

printing(4)

1 
2 2 
3 3 3 
4 4 4 4 


In [6]:
# Ex 23
# Printing first 10 natural numbers using While loop
i = 0
while i<10:
    for i in range(1,15):
        print(i, end = ' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [7]:
# Ex 25
# Accepting numbers till user input is 0, then print sum and average

suming = 0
cnting = 0

while True:
    x = input("Please enter a number: ")
    if int(x)==0:
        print(f"Sum of all numbers are {suming} and average is {round(suming/cnting,2)}")
        break
    else:
        suming+=int(x)
        cnting+=1

Please enter a number: 23
Please enter a number: 23
Please enter a number: 23
Please enter a number: -2
Please enter a number: 0
Sum of all numbers are 67 and average is 16.75


In [8]:
# Ex 26
# Print first 25 Odd number
i = 1
while True:
    if i%2==1:
        print(i,end=' ')
        i+=1
    else:
        i+=1
    if i==25:
        break

1 3 5 7 9 11 13 15 17 19 21 23 

In [9]:
# Ex 27
# Print followin pattern

def triangle(n):
    for i in range(1,n+1):
        for k in range(1,i+1):
            print(k,end = ' ')
        print()
triangle(6)


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 


In [10]:
# Ex 28
# Print following pattern

def simultaneously(n):
    for i in range(1,n+1):
        for k in range(1,i+1):
            tll_sm = sum(range(1,i))
            print(k+tll_sm,end=' ')
        print()
            
simultaneously(5)

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [11]:
# Ex 28
# Easier Solution


def simultaneously(n):
    st = 1
    for i in range(0,n):
        for k in range(0,i+1):
            print(st,end=' ')
            st+=1
        print()
simultaneously(5)        

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [16]:
# Reverse one of the sequence

def inputing(n):
    for i in range(n,0,-1): 
        for k in range(i,0,-1):
            print(k,end=' ')
        print()

inputing(4)

4 3 2 1 
3 2 1 
2 1 
1 


### Pascal Triangle, waiting ....

In [52]:
# Ex 29
# Pascal Triangle

n = 5
triangle = [1]

for i in range(0,n):
    # Displaying one row
    sep = n+1-i
    print(" "*sep,end="")
    for j in range(0,i+1):
        if j==0 or j==i:
            print(triangle[j],end=" ")
        else:
            print(triangle[j]+triangle[j-1],end=" ")
        print()
    
    # Updating Triangle
    nw_cp = triangle.copy()
    nw_arr = [1]*(len(triangle)+1)
    for k in range(len(triangle)+1):
        if k==0 or k==len(triangle):
            triangle.append(1)
        else:
            triangle[k]=triangle[k]+triangle[k-1]
    triangle = nw_arr

      1 
     1 
1 
    1 
2 
1 
   1 
2 
2 
1 
  1 
2 
2 
2 
1 


In [58]:
# Chat GPT solution


def print_symmetric_pascal_triangle(n):
    # Function to calculate factorial
    def factorial(num):
        if num == 0:
            return 1
        else:
            return num * factorial(num - 1)

    # Function to calculate binomial coefficient
    def binomial_coefficient(n, k):
        return factorial(n) // (factorial(k) * factorial(n - k))

    # Loop to iterate through each row of Pascal's triangle
    for i in range(n):
        # Print leading spaces to center the triangle
        print(" " * (n - i - 1), end=" ")

        # Loop to print each element of the current row
        for j in range(i + 1):
            print(binomial_coefficient(i, j), end=" ")
        print()

# Example usage:
print_symmetric_pascal_triangle(10)

          1 
         1 1 
        1 2 1 
       1 3 3 1 
      1 4 6 4 1 
     1 5 10 10 5 1 
    1 6 15 20 15 6 1 
   1 7 21 35 35 21 7 1 
  1 8 28 56 70 56 28 8 1 
 1 9 36 84 126 126 84 36 9 1 


In [14]:
# Ex 36
# Display prime numbers from x to y
# 1 is not a prime numbner

def prime_list(start,end):
    prms = []
    for i in range(start,end+1):
        cnting = 0
        for k in range(1,i+1):
            if i%k==0:
                cnting+=1
        if cnting==2:
            prms.append(i)
    return prms

for k in prime_list(1,100):
    print(k,end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [16]:
# Ex 37
# Fibonacci sequence, another solution

def fibo_seq(n):
    num1 = 0
    num2 = 1
    print(num1,num2,end=" ")
    for i in range(n):
        # ასეთ სტილშიც მოსულა რორამე
        num3 = num1+num2
        num1,num2 = num2,num3
        print(num3,end=" ")

fibo_seq(9)

0 1 1 2 3 5 8 13 21 34 55 

In [17]:
# Ex 42
# Sums 2's

def two_sum(n):
    sming = 0
    for i in range(1,1+n):
        cr = int('2'*i)
        sming+=cr
    return sming

two_sum(5)

24690

In [18]:
# Ex 43
# Half-Pyramid asterisk

def asterisk(n):
    for i in range(n,0,-1):
        print("* "*i)

def asterisk_2(n):
    for i in range(n,0,-1):
        for k in range(i,0,-1):
            print("*",end=' ')
        print()

asterisk(5)
print()
asterisk_2(5)

* * * * * 
* * * * 
* * * 
* * 
* 

* * * * * 
* * * * 
* * * 
* * 
* 


In [19]:
# Ex 44
# Right Half side of Pyramid

n = 6

for i in range(1,n+1):
    for k in range(1,i+1):
        print("*",end=' ')
    print()


* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 


In [20]:
# Ex 45
# Printing Pyramid
def christmas_tree(n):    
    for i in range(1,n+1):
        mx = n
        whitesp =(mx-i)
        print(" "*whitesp,end="")
        for k in range(1,i+1):
            print("*", end=" ")
        print()

christmas_tree(7)

      * 
     * * 
    * * * 
   * * * * 
  * * * * * 
 * * * * * * 
* * * * * * * 


In [21]:
# Ex 46
# * task, something like rocket triangle 
# N should be odd

def rocket_triangle(n):
    if n%2==0:
        print("Please enter odd number.")
    else:
        middle = n//2+1    
        for i in range(1,n+1):
            times = middle - abs(i-middle)
            for k in range(1,times+1):
                print("*",end=" ")
            print()

rocket_triangle(11)

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


### Python Functions Excercises, PG 39

In [23]:
# Ex 17
# Strong number --> sum of each digit factorial is its number

def strong_number(n):
    to_str = str(n)
    sming = 0
    for i in to_str:
        fac_sum = 1
        for t in range(1,int(i)+1):
            fac_sum *= t
        sming+= fac_sum
    if sming==n:
        return True
    else:
        return False
    
strong_numbers = list(filter(strong_number,range(1,50000)))

for k in strong_numbers:
    print(k, end=" ")

1 2 145 40585 

In [24]:
# Ex 18
# Perfect Number

def perfect_number(n):
    sming = 0
    for i in range(1,n):
        if n%i==0:
            sming+=i
    if sming==n:
        return True
    else:
        return False
    
perf_numbers = list(filter(perfect_number,range(1,1001)))
perf_numbers


[6, 28, 496]

### Python String Excercises, PG 48

In [25]:
# Ex 1
# How many times given substring happens in string
string = 'giorgi kargi biwia hah giorgi'
substring = 'giorgi'
string.count(substring)

2

In [67]:
# Ex 10
#Lower cases appear first
string_t =  'Hello World'
def first_lower(string):
    emp_arr = []
    addition = []
    string_t = string.replace(' ','')
    for i in string_t.replace(' ',''):
        if i.islower():
            emp_arr.append(i)
        else:
            addition.append(i)
    emp_arr.extend(addition)
    return ''.join(emp_arr)

first_lower('Hello world')

'elloworldH'

In [27]:
# Ex 12
# Mixed String
# Length of both strings are same
def mixed_str(str1,str2):
    fin_wr = ''
    for i in range(len(str1)):
        fin_wr+=str1[i]+str2[-i-1]
    return fin_wr

mixed_str('xyz','ABC')

'xCyBzA'

In [29]:
# Ex 13
# Balanced strings

def balanced_str(str1,str2):
    cnting = 0
    for i in str1:
        if i in str2:
            cnting+=1
    if cnting==len(str1):
        return True
    else:
        return False
    
balanced_str('giok','giorgi')

False

In [30]:
# Ex 14
# all occurances of given substring is String

def all_occurances(substring,string):
    occur = []
    starter = 0
    while True:
        curr = string.find(substring,starter)
        if curr==-1:
            break
        else:
            occur.append(curr)
            starter = curr+1
    return occur

all_occurances('gio','gio magari biwio gio sagol ra gio')


[0, 17, 30]

In [88]:
# String to title case, without title() function

def title_case(string):
    splt = string.split(' ')
    fin_str = ''
    for i in splt:
        fin_str+=i.capitalize()+' '
    return fin_str

print(title_case('giorgi kai kaco'))

Giorgi Kai Kaco 


In [31]:
# Ex 16
# Sum and average of digis in string

def sum_avg(string):
    lst_comp = [int(i) for i in string if i.isdigit()]
    sming = sum(lst_comp)
    average = sming / len(lst_comp)
    return sming, average

sum_avg('231daadfa23201')

(14, 1.75)

In [222]:
# Ex 21
import re
sentence = '/*Jon is developer@'
class_sentence = re.sub('[^A-Za-z0-9\s]',"",sentence)
class_sentence

'Jon is developer'

In [218]:
# Ex 24
import string
str1 = '/*jon @ developer'
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [32]:
# Ex 25
# Extracting starters without @ 
lst_t = ['go@go.20','no@gak.23']

for i in lst_t:
    # ასეთი რაღაცეები Data-სთან მუშაობს დროს გამომადგება
    pr = i.replace('@','').split('.')
    print(pr[0])

gogo
nogak


### Python Data Structure Excercises, PG 61

In [2]:
# Ex 1
# odds from first and evens from second

def odd_even(lst1,lst2):
    fin_lst = []
    
    for i in lst1[::2]:
        fin_lst.append(i)
    for k in lst2[1::2]:
        fin_lst.append(k)
    return fin_lst

list_1 = [1,2,3,4,5]
list_2 = [1,2,3,4,5]
odd_even(list_1,list_2)

[1, 3, 5, 2, 4]

In [10]:
# Ex 3
# 3 Equal chunks
test_ls = [11,23,24,5,-3,5,24,1,24]
n = 3

output = [test_ls[i:i+n] for i in range(0,len(test_ls),n)]
output


[[11, 23, 24], [5, -3, 5], [24, 1, 24]]

In [13]:
# Ex 4
# Count of each occurance

test_ls = [11,23,24,5,-3,5,24,1,24]
count = {}
for i in test_ls:
    if i in count:
        count[i]+=1
    else:
        count[i]=1

count        


{11: 1, 23: 1, 24: 3, 5: 2, -3: 1, 1: 1}

In [15]:
# Ex 5
# Zipping

lst_1 = [1,2,3]
lst_2 = [1,2,3]

list(zip(lst_1,lst_2))

[(1, 1), (2, 2), (3, 3)]

In [18]:
# Ex 7
# Checking existance


roll_number = [45,34,23,37]
sample_dict = {'John':47,'Giorgi':23}

roll_number[:] = [item for item in roll_number if item in sample_dict.values()]
roll_number

[23]

### Python List Excercises, PG 66

In [20]:
# Ex 10
# Remove empty strings

def remove_empty(list_t):
    nw_lst = list(filter(lambda x: x!='',list_t))
    return nw_lst

remove_empty([1,2,3,""])



[1, 2, 3]

In [25]:
# Ex 11
list1 = [10,20,[300,400,[10,10],500],20]
list1[2][2].append(700)
list1

[10, 20, [300, 400, [10, 10, 700], 500], 20]

In [31]:
# Ex 18
# Shuffle a list
from random import shuffle
lst_t = ['gio','nika','sulo','sandro']
shuffle(lst_t)
lst_t



['sulo', 'gio', 'sandro', 'nika']

### Dictionary, PG 73

In [33]:
# Ex 2
# Convert into  dictionary
keys = ['a','b','c']
values = [10,20,30]
my_dict = dict(zip(keys,values))
my_dict

{'a': 10, 'b': 20, 'c': 30}

In [47]:
# Ex 3
# Merging into one dictionary
my_dict2 = {'d':40,'e':50}


new = {**my_dict,**my_dict2}
new



{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [50]:
# Ex 5

employees = ['Kelly','Emma']
defaults = {"deisgnation":"Developer","Salary":8000}
result = dict.fromkeys(employees,defaults)
print(result)


{'Kelly': {'deisgnation': 'Developer', 'Salary': 8000}, 'Emma': {'deisgnation': 'Developer', 'Salary': 8000}}


In [56]:
# Ex 8
# Rename key
# Interesting approach

sample_dict = {"Name":"kelly","age":25,"City":"New york"}
sample_dict["Location"] = sample_dict.pop("City")
sample_dict

{'Name': 'kelly', 'age': 25, 'Location': 'New york'}

In [70]:
# Ex 10
# Minimum of values

sample_dict = {"A":10,"B":20,"C":30}
x = min(sample_dict.values())
# Interesting Appraoch

min(sample_dict, key = sample_dict.get)

for i,v in sample_dict.items():
    if v==x:
        print(i)

A


### Set Exercises, PG 79

### Tuple Exercises, PG 83

In [72]:
# Ex 3
# One element tuplet
tup_1 = ('a',)
tup_1, type(tup_1)


(('a',), tuple)

In [78]:
# Ex 7

tup_tst = (11,[23,24],5)
tup_tst[1][0]=2
tup_tst

(11, [2, 24], 5)

In [80]:
# Ex 8
# Sorting tuple
tpl_t = (('a',23),('b',15),('c',23))
srt_t = sorted(tpl_t,key = lambda x:x[1])
srt_t



[('b', 15), ('a', 23), ('c', 23)]

In [83]:
# Ex 10
# Check if all items are the same
t = (45,45,45,45)
all_same = all(i==t[0] for i in t)
all_same


True

### NumPy, PG 104

In [89]:
import numpy as np
# Ex 1
arr_tst = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.max(arr_tst), np.max(arr_tst,axis=0),np.max(arr_tst,axis=1)

(9, array([7, 8, 9]), array([3, 6, 9]))

In [97]:
# Ex 2
# Integer array
emp_arr = np.empty((2,4),int)
emp_arr, emp_arr.size, emp_arr.shape, emp_arr.ndim

(array([[    0,     1,     0,   629],
        [ 1540,     0,   768, 32766]]),
 8,
 (2, 4),
 2)

In [105]:
# Ex 3
np_arr = np.arange(10,102,10)
np_arr.reshape(5,2,order="C")

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [107]:
np_arr.reshape(2,5).transpose()

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

In [141]:
# Ex 7
# Split ndarray

np_tst = np.random.randint(0,100,(4,4))
x,y,z,t = np.split(np_tst,4)
x,y,z,t

(array([[73, 96, 49, 53]]),
 array([[73,  8, 52, 30]]),
 array([[79, 14, 92, 58]]),
 array([[74, 22,  3, 91]]))

In [145]:
# Ex 8
# Sort array by row 2
np.random.seed(40)
np_tst = np.random.randint(0,100,(4,4))
sorted_array = np_tst[:,np_tst[1,:].argsort()]
sorted_array, np_tst


(array([[37, 91, 70,  7],
        [12, 50, 56, 65],
        [74, 19, 71, 31],
        [91, 83, 55, 59]]),
 array([[70, 91,  7, 37],
        [56, 50, 65, 12],
        [71, 19, 31, 74],
        [55, 83, 59, 91]]))

### Random Data Generation, PG 132

In [150]:
# Ex 1
# Generate from 100 to 999, which is divisible by 5
import random
for i in range(3):
    print(random.randrange(100,999,5))

765
915
645


In [154]:
# Ex 2
# Generate 100 ticket and choose 2 randomly
lottery_ticket = []

for i in range(100):
    lottery_ticket.append(random.randrange(10000,99999))
winners = random.sample(lottery_ticket,2)
winners



[46293, 72083]

In [173]:
# Ex 4
# Pick random letter
name = 'Giorgi'

for i in range(10):
    x = random.choice(name)
    print(x,end=" ")

i i g o o o i i i r 

In [182]:
# Ex 5

import string
letters = string.ascii_letters
fin_wr = ''
for i in range(5):
    x = random.choice(letters)
    fin_wr+=x
print(fin_wr)

SwvKC


In [200]:
# Ex 6
# Generate random passwor
# 10 chars long, 2 uppercase, 1 digit, 1 special char

random_source = string.ascii_letters + string.digits + string.punctuation  
# 6 random first
password = random.sample(random_source,6)
# two uppercase
password += random.sample(string.ascii_uppercase,2)
# one digit
password += random.sample(string.digits,1)
# one special
password += random.sample(string.punctuation,1)

password_list = list(password)
shuffle(password_list)
''.join(password_list)


'.4Es=CRCMz'

In [215]:
# Ex 7
nrd_rn = random.uniform(9.5,99.5)
nrd_rn

59.34915116933875